name: compute_gene_scores
description: calculate gene set enrichment scores using multiple methods.
keywords:
  - bioinformatics tools
tools:
  - compute_gene_scores:
      description: |
        Compute gene scores calculates gene set scores using various methods such as Singscore, GSVA, SSGSEA, PLAGE, and Samsscore.
        It includes multiple gene set transformations and scoring techniques.
input:
  - - counts:
        type: file
        description: |
          A matrix or data frame containing normalized gene counts data.
        pattern: "*normalized_counts.tsv"
  - - geneset_yaml:
        type: file
        description: |
          This sets the YAML to be used for computing the gene scores. Needs both a name for each set of genes and respective genes to be selected.
output:
  - scores_for_mqc:
      - "*.txt":
        type: file
        description: |
          A file containing the calculated scores to be used to create the MultiQC report.
        pattern: "*.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@apeltzer"
  - "@christopher-mohr"
maintainers:
  - "@nschcolnicov"
